spring:
  application:
    name: user-service
  config:
    import: optional:consul:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
  datasource:
    url: jdbc:mysql://localhost:3306/microservices?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
  sql:
    init:
      mode: never
  cache:
    type: simple
server:
  port: 8083
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

